### ISSUE TITLE
Download / List Unicode problem..

### ISSUE THREAD

**Issue by fabwa** [andreafabrizi/Dropbox-Uploader#139]
Aloah, thanks for this nice piece of code, highly appreciate your effort.
Unfortunately i have Problems with a small bug:

If i try to recursively download a folder containing files with names containing special characters from non englisch language (e.g. ÄÜÖäüö german characters) the files fail to download. If i do a listing i see that the characters are converted to codes and therefore also cannot be retrieved during download.
OrzFly suggested the Problem lies in the following lines:

"I took a glance at the file, and I think this bug is related with dropbox_uploader.sh#L644 and dropbox_uploader.sh#L910."

Maybe someone capable out there knows a quick fix (dont mind if its dirty or hardcoded für bunch of characters..)

Thank you :-)

**Comment by LinusSong** [comment]
Hi, I tested the script on Raspberry Pi 2 and it has the same problem.
 $ builtin printf "Test_\u00dc\n"
Test_▒
$ /usr/bin/printf "Test_\u00dc\n"
Test_Ü
It seems that the builtin printf doesn't supports unicode chars. 
But if I replace all $PRINTF with  /usr/bin/printf, the script cannot work either.
Therefore, could you give me some suggestions when both builtin and external printf don't work?

**Comment by Ivanca** [comment]
I fixed this issue, in my case this was not a problem with printf but with the system "locale", I added the following lines to my `~/.profile` file:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
And then I executed `source ~/.bashrc` and then the the issue got fixed. To read more about this fix: http://perlgeek.de/en/article/set-up-a-clean-utf8-environment

**Comment by LinusSong** [comment]
@Ivanca It doesn't work on my Raspberry Pi 2.
However, it really has some effect on builtin printf. Now the output becomes:
```
$ builtin printf "Test_\u00dc\n"
Test_
```
Well, maybe I should try another OS. The default OS Raspbian has some weird bugs.

**Comment by dj2mn** [comment]
Hi - I've got the latest version of dropbox_uploader.sh but I'm still having issues with unicode characters. I'm on OSX High Sierra now but the issue has been bugging me [pardon the pun] since at least 2 releases back. Using the test above I get:

```
$ builtin printf "Test_\u00dc\n"
Test_\u00dc
$ /usr/bin/printf "Test_\u00dc\n"
Test_u00dc
```

and for what it's worth, 

```
$ locale
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL="en_AU.UTF-8"

```

I've looked all over for some OSX/BSD specific advice but if it's there I'm not finding it. 

This is really only bothering me when I back up my iTunes library, otherwise it's a terrific and useful script, keep up the good work! :)
