### ISSUE TITLE
Access Token request...  FAILED

### ISSUE THREAD

**Issue by JoinJoin** [andreafabrizi/Dropbox-Uploader#216]
For some reason it fails. 
I have followed your instructions,
I Create App and select Dropbox API app but there is no option like "Files and datastores" but I can select either: 
Can your app be limited to its own folder?: 
1) Yes - My app only needs access to files it creates.
2) No -  My app needs access to files already on Dropbox.

I selected 1. and continued with set up. 

I get to the URL, enter this to web browser and confirm access 

" Success! ******** is connected to your Dropbox."

Back to commandline:
 
Press enter when done...

 > Access Token request...  FAILED

**Comment by andreafabrizi** [comment]
@JoinJoin, the setup procedure works fine. Probably you have selected the wrong permission type?
Please try again with the new version just pushed, I've fixed the setup procedure texts.

**Comment by JoinJoin** [comment]
Still fails. 
1) I log in to dropbox, https://www.dropbox.com/developers/apps
2) I select Dropbox API app 
3) select - Yes My app only needs access to files it creates.
4) Provide an app name, and you're on your way: I add a random name 
5) start updated script 
6) I copy/paste the App key :
7) I copy/paste the App secret:
8) Permission type: "a"  
9) I confirm the key etc. 
10)  Token request... OK
11 )  Please open the following URL in your browser, and allow Dropbox Uploader
 to access your DropBox folder:

 --> https://www.dropbox.com/1/oauth/authorize?oauth_token=R******
12) I authorize the app i created 
13) I press "enter" 
14) and I get " Access Token request...  FAILED" 

and it give me exactly the same URL as before: Please open the following URL in your browser, and allow Dropbox Uploader to access your DropBox folder

I am out of ideas :(

**Comment by JoinJoin** [comment]
Maybe you can write few lines of code so we can have more verbose log from the 

....
 Press enter when done...
 >  Access Token request... 

and tell me where to insert it.

**Comment by andreafabrizi** [comment]
please run the script in debug mode (-d) and send me the output.

**Comment by JoinJoin** [comment]
Hopefully this helps to get to the bottom of this. 

`
Press enter when done...
+ read

+ echo -ne ' > Access Token request... '
 > Access Token request... ++ utime
+++ date +%s
++ echo 1433858094
+ curl -s --show-error --globoff -i -o /tmp/du_resp_debug --data 'oauth_consumer_key=70zlyBLAH&oauth_token=BLAHGA&oauth_signature_method=PLAINTEXT&oauth_signature=got8BLAHqa0uh%26M&oauth_timestamp=1433858094&oauth_nonce=28326' https://api.dropbox.com/1/oauth/access_token
+ check_http_response
+ CODE=0
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
++ sed -n 's/oauth_token_secret=\([a-z A-Z 0-9]*\)&.*/\1/p' /tmp/du_resp_debug
+ OAUTH_ACCESS_TOKEN_SECRET=
++ sed -n 's/.*oauth_token=\([a-z A-Z 0-9]*\)&.*/\1/p' /tmp/du_resp_debug
+ OAUTH_ACCESS_TOKEN=
++ sed -n 's/.*uid=\([0-9]*\)/\1/p' /tmp/du_resp_debug
+ OAUTH_ACCESS_UID=
+ [[ '' != '' ]]
+ print ' FAILED\n'
+ [[ 0 == 0 ]]
+ echo -ne ' FAILED\n'
 FAILED
+ ERROR_STATUS=1
+ true
+ echo -ne '\n Please open the following URL in your browser, and allow Dropbox Uploader\n'

 Please open the following URL in your browser, and allow Dropbox Uploader
+ echo -ne ' to access your DropBox folder:\n\n --> https://www.dropbox.com/1/oauth/authorize?oauth_token=ZOD2ocDELAnADcGA\n'
 to access your DropBox folder:

 --> https://www.dropbox.com/1/oauth/authorize?oauth_token=ZOD2ocDELAnADcGA
+ echo -ne '\nPress enter when done...\n'

Press enter when done...
+ read `

**Comment by JoinJoin** [comment]
maybe this is helpful:
```
$cat /tmp/du_resp_debug 

HTTP/1.1 401 Unauthorized
Server: nginx
Date: Tue, 09 Jun 2015 14:15:56 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
WWW-Authenticate: OAuth realm="https://api.dropbox.com/"
X-Dropbox-Request-Id: ba771afa3eBLAHe39bc

{"error": "Unauthorized"}
```

**Comment by JoinJoin** [comment]
Why is this marked Closed?

**Comment by JoinJoin** [comment]
Any ideas how to resolve this problem? 

Can you please change the status form Closed to Reopend so it become visible in your bugs list and hopefully someone else can help.

Thank you

**Comment by emlazzarin** [comment]
I'm facing the exact same issue. I've followed the instructions to the last letter, and even checked debug mode, without any clues.

**Comment by JoinJoin** [comment]
emlazzarin, any luck finding out what causes this?

**Comment by cdbessig** [comment]
Same issue here.

**Comment by AndyMAu** [comment]
I am having the same issue. Token request ... FAILED :(

**Comment by markur** [comment]
Having the same issue from my Mac using Terminal. El Capitan. Has this issue been fixed or is it just DOA now?

**Comment by cdbessig** [comment]
Hello,

Thank you for your email. Please note, 7/5 - 7/16, I will be travelling internationally,with limited and times of no access to email.  As such, responses may be delayed by 1-2 business days. 

If the request is URGENT and requires immediate or same day support please reach out to the following contacts below.

For all support issues, please contact: support@creatingdigital.com or by phone 201-475-1288

Account Management
Damian Gonzalez
dgonzalez@creatingdigital.com
Direct Phone #: 201-475-1288

Technical Contact/ Urgent Server Issues
Raymond Gonzalez
rgonzalez@creatingdigital.com
Direct Phone #: 201-475-1288

Tim Haas
thaas@creatingdigital.com
Direct Phone #: 201-475-1288

Thank you for your understanding.

**Comment by markur** [comment]
This is what I get with debug mode:
> Token request... ++ utime
+++ date +%s
++ echo 1467870058
+ curl -L -s --show-error --globoff -i -o /tmp/du_resp_debug --data 'oauth_consumer_key=d5ulsrumh6brbpl&oauth_signature_method=PLAINTEXT&oauth_signature=ou9ix1kypOgcjqt%26&oauth_timestamp=1467870058&oauth_nonce=8067' https://api.dropbox.com/1/oauth/request_token
+ check_http_response
+ CODE=0
+ case $CODE in
+ grep -q 'HTTP/1.1 400' /tmp/du_resp_debug
++ sed -n 's/oauth_token_secret=\([a-z A-Z 0-9]*\).*/\1/p' /tmp/du_resp_debug
+ OAUTH_TOKEN_SECRET=
++ sed -n 's/.*oauth_token=\([a-z A-Z 0-9]*\)/\1/p' /tmp/du_resp_debug
+ OAUTH_TOKEN=
+ [[ '' != '' ]]
+ echo -ne ' FAILED\n\n Please, check your App key and secret...\n\n'
 FAILED

 Please, check your App key and secret...

+ remove_temp_files
+ [[ 1 == 0 ]]
+ exit 1

**Comment by andreafabrizi** [comment]
It should be fixed in the last version.

**Comment by cdbessig** [comment]
Hello,

Thank you for your email. Please note, I will be out from 8/12 - 8/17, with ZERO access to email.  As such responses may be delayed or not responded to until my return.  If you require a response during that time, please reach out to the below contacts.

For all support issues, please contact: support@creatingdigital.com or by phone 201-475-1288


Account Management Support
Damian Gonzalez
dgonzalez@creatingdigital.com
Direct Phone: 201-475-1288

Technical Contact/ Urgent Server Issues
Raymond Gonzalez
rgonzalez@creatingdigital.com
Direct Phone #: 201-475-1288
Cell Phone #: 201-232-7836


Thank you for your understanding.

-- 
Brian Essig
Creating Digital LLC
http://www.creatingdigital.com
201-475-1288 (p)
201-616-7077 (f)
